name = "Rasterizer"
uuid = "b439dc22-a469-4784-aca3-0851293fc6d2"
authors = ["Cody Sevier <sevierit@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SimpleDirectMediaLayer = "98e33af6-2ee5-5afd-9e75-cbc738b767c4"

[compat]
LinearAlgebra = "1.11.0"
SimpleDirectMediaLayer = "0.5.0"
